<a href="https://colab.research.google.com/github/aniruddhabhagwatkar/Data_Science_Lab_SE_04/blob/main/practical_08.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
# Load the ratings data
ratings_df = pd.read_csv('/content/rating.csv')

print("Ratings DataFrame head:")
display(ratings_df.head())

Ratings DataFrame head:

   userId  movieId  rating            timestamp
0       1        2     3.5  2005-04-02 23:53:47
1       1       29     3.5  2005-04-02 23:31:16
2       1       32     3.5  2005-04-02 23:33:39
3       1       47     3.5  2005-04-02 23:32:07
4       1       50     3.5  2005-04-02 23:29:40

In [ ]:
# Load the movies data
movies_df = pd.read_csv('/content/movie.csv')

print("Movies DataFrame head:")
display(movies_df.head())

Movies DataFrame head:

,movieId,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,Father of the Bride Part II (1995),Comedy

In [ ]:
# Merge ratings and movies dataframes
merged_df = pd.merge(ratings_df, movies_df, on='movieId', how='left')

print("Merged DataFrame head:")
display(merged_df.head())

Merged DataFrame head:

,userId,movieId,rating,timestamp,title,genres
0,1,2,3.5,2005-04-02 23:53:47,Jumanji (1995),Adventure|Children|Fantasy
1,1,29,3.5,2005-04-02 23:31:16,"City of Lost Children, The (Cité des enfants p...",Adventure|Drama|Fantasy|Mystery|Sci-Fi
2,1,32,3.5,2005-04-02 23:33:39,Twelve Monkeys (a.k.a. 12 Monkeys) (1995),Mystery|Sci-Fi|Thriller
3,1,47,3.5,2005-04-02 23:32:07,Seven (a.k.a. Se7en) (1995),Mystery|Thriller
4,1,50,3.5,2005-04-02 23:29:40,"Usual Suspects, The (1995)",Crime|Mystery|Thriller

In [ ]:
# Merge datasets
df = pd.merge(ratings_df, movies_df, on='movieId')

df.head()

,userId,movieId,rating,timestamp,title,genres
0,1,2,3.5,2005-04-02 23:53:47,Jumanji (1995),Adventure|Children|Fantasy
1,1,29,3.5,2005-04-02 23:31:16,"City of Lost Children, The (Cité des enfants p...",Adventure|Drama|Fantasy|Mystery|Sci-Fi
2,1,32,3.5,2005-04-02 23:33:39,Twelve Monkeys (a.k.a. 12 Monkeys) (1995),Mystery|Sci-Fi|Thriller
3,1,47,3.5,2005-04-02 23:32:07,Seven (a.k.a. Se7en) (1995),Mystery|Thriller
4,1,50,3.5,2005-04-02 23:29:40,"Usual Suspects, The (1995)",Crime|Mystery|Thriller

In [ ]:
genre = "Action"

genre_df = df[df['genres'].str.contains(genre)]

genre_df.head()

,userId,movieId,rating,timestamp,title,genres
5,1,112,3.5,2004-09-10 03:09:00,Rumble in the Bronx (Hont faan kui) (1995),Action|Adventure|Comedy|Crime
6,1,151,4.0,2004-09-10 03:08:54,Rob Roy (1995),Action|Drama|Romance|War
9,1,260,4.0,2005-04-02 23:33:46,Star Wars: Episode IV - A New Hope (1977),Action|Adventure|Sci-Fi
10,1,293,4.0,2005-04-02 23:31:43,Léon: The Professional (a.k.a. The Professiona...,Action|Crime|Drama|Thriller
14,1,367,3.5,2005-04-02 23:53:00,"Mask, The (1994)",Action|Comedy|Crime|Fantasy

In [ ]:
avg_rating = genre_df['rating'].mean()
print(f"Average rating for {genre} movies:", avg_rating)

Average rating for Action movies: 3.44386376493354

In [ ]:
# Take a smaller sample for faster processing
df_sample = df.sample(10000, random_state=42)

# Ensure genres column is clean
df_sample['genres'] = df_sample['genres'].fillna('').astype(str)

# Create dummy variables
genres_dummies = df_sample['genres'].str.get_dummies(sep='|')

# Combine with ratings
model_df = pd.concat([df_sample[['rating']], genres_dummies], axis=1)

model_df.head()

,rating,Action,Adventure,Animation,Children,Comedy,Crime,Documentary,Drama,Fantasy,Film-Noir,Horror,IMAX,Musical,Mystery,Romance,Sci-Fi,Thriller,War,Western
17679788,3.5,0,1,1,1,1,0,0,0,0,0,0,0,1,0,1,0,0,0,0
7106385,2.0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,1,0,0
12970708,3.5,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0
15426752,3.0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0
6934678,2.0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

X = model_df.drop('rating', axis=1)
y = model_df['rating']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

model = LinearRegression()
model.fit(X_train, y_train)

LinearRegression()

In [ ]:
# Create input for prediction
input_data = pd.DataFrame([{
    col: 1 if col == "Action" else 0 for col in X.columns
}])

predicted_rating = model.predict(input_data)

print("Predicted Rating for Action movie:", predicted_rating[0])

Predicted Rating for Action movie: 3.2947850741623648

In [ ]:
from sklearn.metrics import mean_squared_error

y_pred = model.predict(X_test)
print("MSE:", mean_squared_error(y_test, y_pred))

MSE: 1.0399101067686096